const fs = require('fs');
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

const entry = './src/index.js';// the entry point of the app

const main = process.env.NODE_ENV === "development" ? [
    // bundle the client for webpack-dev-server
    // and connect to the provided endpoint
    `webpack-dev-server/src?http://localhost:5000`,
    entry
] : [entry];

module.exports = {
    entry: {
        main,
        vendor: [
            'immutable',
            'react-dom',
            'react-redux',
            'react',
            'redux',
        ],
    },
    output: {
        path: __dirname + `/public`,
        filename: '[name].js',
        publicPath: '/'
    },
    module: {
        rules: [
            {
                test: /\.(ttf|eot|otf|svg|png|gif|woff2|woff|jpg(2)?)(\?[a-z0-9]+)?$/,
                loader: 'file-loader'
            },
            {
                test: /\.css$/,
                exclude: [/styles.css/],
                use: [
                    'style-loader',
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true,
                            modules: true,
                            importLoaders: 1,
                            localIdentName: '[name]__[local]___[hash:base64:5]',
                        },

                    },
                ]
            },
            {
                test: [/styles.css/],
                use: [
                    'style-loader',
                    {loader: 'css-loader'}
                ]
            },
            {
                test: /\.js/,
                exclude: /node_modules/,
                loader: 'babel-loader',
            }
        ]
    },
    resolve: {
        extensions: ['.js'],
        modules: ['node_modules', path.join(__dirname, "src")],
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            names: ['vendor', 'manifest'] // Specify the common bundle's name.
        }),
        new HtmlWebpackPlugin({
            template: 'index.html',
            inject: true // Inject all files that are generated by webpack, e.g. bundle.js
        }),
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
            }
        })
    ],
    externals: {
        cheerio: 'window',
        'react/addons': 'react',
        'react/lib/ExecutionEnvironment': 'react',
        'react/lib/ReactContext': 'react',
        'react-addons-test-utils': 'react-dom',
    }
};
